// Generated by BUCKLESCRIPT VERSION 5.0.2, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");

function Button(Props) {
  var handleClick = Props.handleClick;
  var children = Props.children;
  var internalClick = function (_e) {
    return Curry._1(handleClick, /* () */0);
  };
  return React.createElement("button", {
              onClick: internalClick
            }, children);
}

var make = Button;

exports.make = make;
/* react Not a pure module */
