// Generated by BUCKLESCRIPT VERSION 5.0.2, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Emotion = require("bs-emotion/src/Emotion.bs.js");

var title = Emotion.css(undefined, /* :: */[
      Emotion.label("title"),
      /* :: */[
        Emotion.height(/* `rem */[
              5691738,
              2.0
            ]),
        /* :: */[
          Emotion.fontSize(/* `rem */[
                5691738,
                2.0
              ]),
          /* :: */[
            Emotion.color(/* `hex */[
                  5194459,
                  "569462"
                ]),
            /* [] */0
          ]
        ]
      ]
    ]);

var Style = /* module */[/* title */title];

function Display(Props) {
  var text = Props.text;
  return React.createElement("h1", {
              className: title
            }, text);
}

var make = Display;

exports.Style = Style;
exports.make = make;
/* title Not a pure module */
