// Generated by BUCKLESCRIPT VERSION 5.0.2, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var $$Array = require("bs-platform/lib/js/array.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Button$ReCalc = require("./Button.bs.js");

var nums = /* :: */[
  "1",
  /* :: */[
    "2",
    /* :: */[
      "3",
      /* :: */[
        "4",
        /* :: */[
          "5",
          /* :: */[
            "6",
            /* :: */[
              "7",
              /* :: */[
                "8",
                /* :: */[
                  "9",
                  /* :: */[
                    "0",
                    /* [] */0
                  ]
                ]
              ]
            ]
          ]
        ]
      ]
    ]
  ]
];

function NumButtons(Props) {
  var handleClick = Props.handleClick;
  return React.createElement(React.Fragment, undefined, $$Array.of_list(List.map((function (n) {
                        return React.createElement(Button$ReCalc.make, {
                                    handleClick: (function (param) {
                                        return Curry._1(handleClick, n);
                                      }),
                                    children: n,
                                    key: n
                                  });
                      }), nums)));
}

var make = NumButtons;

exports.nums = nums;
exports.make = make;
/* react Not a pure module */
