// Generated by BUCKLESCRIPT VERSION 5.0.2, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Emotion = require("bs-emotion/src/Emotion.bs.js");

var errMsg = Emotion.css(undefined, /* :: */[
      Emotion.label("errMsg"),
      /* :: */[
        Emotion.height(/* `rem */[
              5691738,
              2.0
            ]),
        /* :: */[
          Emotion.color(/* `hex */[
                5194459,
                "ff5d3b"
              ]),
          /* [] */0
        ]
      ]
    ]);

var Styles = /* module */[/* errMsg */errMsg];

function DisplayError(Props) {
  var error = Props.error;
  return React.createElement("h2", {
              className: errMsg
            }, error !== undefined ? error : "");
}

var make = DisplayError;

exports.Styles = Styles;
exports.make = make;
/* errMsg Not a pure module */
