// Generated by BUCKLESCRIPT VERSION 5.0.2, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");
var React = require("react");
var JestDom = require("bs-jest-dom/src/JestDom.bs.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var Button$ReCalc = require("../src/components/Button.bs.js");
var ReactTestingLibrary = require("bs-react-testing-library/src/ReactTestingLibrary.bs.js");

function noop(param) {
  return /* () */0;
}

Jest.test("renders correctly", (function (param) {
        var element = React.createElement(Button$ReCalc.make, {
              handleClick: noop,
              children: "Submit"
            });
        var partial_arg = /* `Str */[
          4153489,
          "Submit"
        ];
        return JestDom.toBeInTheDocument(Jest.Expect[/* expect */0](Caml_option.some((function (eta) {
                                var param = undefined;
                                var param$1 = eta;
                                return ReactTestingLibrary.getByText(partial_arg, param, param$1);
                              })(ReactTestingLibrary.render(undefined, undefined, element)))));
      }));

exports.noop = noop;
/*  Not a pure module */
